package org.template.domain;
// Generated Apr 7, 2015 6:36:38 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Assignedproduct generated by hbm2java
 */
public class Assignedproduct implements java.io.Serializable {

    private Integer assignedProductId;
    private Integer productId;
    private Integer userId;
    private Date doe;
    private Integer byUserId;

    public Assignedproduct() {
    }

    public Integer getAssignedProductId() {
        return assignedProductId;
    }

    public void setAssignedProductId(Integer assignedProductId) {
        this.assignedProductId = assignedProductId;
    }

    public Integer getProductId() {
        return productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Date getDoe() {
        return doe;
    }

    public void setDoe(Date doe) {
        this.doe = doe;
    }

    public Integer getByUserId() {
        return byUserId;
    }

    public void setByUserId(Integer byUserId) {
        this.byUserId = byUserId;
    }

}
