package org.template.domain;
// Generated Apr 7, 2015 6:36:38 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sprintbacklog generated by hbm2java
 */
public class SprintBacklog implements java.io.Serializable {

    private Integer sprintBacklogId;
    private Integer productBacklogId;
    private Integer sprintId;
    private String size;
    private Date doe;
    private Integer byUserId;

    public SprintBacklog() {
    }

    public Integer getByUserId() {
        return byUserId;
    }

    public void setByUserId(Integer byUserId) {
        this.byUserId = byUserId;
    }

    public Integer getSprintBacklogId() {
        return sprintBacklogId;
    }

    public void setSprintBacklogId(Integer sprintBacklogId) {
        this.sprintBacklogId = sprintBacklogId;
    }

    public Integer getProductBacklogId() {
        return productBacklogId;
    }

    public void setProductBacklogId(Integer productBacklogId) {
        this.productBacklogId = productBacklogId;
    }

    public Integer getSprintId() {
        return sprintId;
    }

    public void setSprintId(Integer sprintId) {
        this.sprintId = sprintId;
    }

    public String getSize() {
        return size;
    }

    public void setSize(String size) {
        this.size = size;
    }

    public Date getDoe() {
        return doe;
    }

    public void setDoe(Date doe) {
        this.doe = doe;
    }

}
